name: WelcomeTitlePlugin
version: 1.2
main: tech.raic.welcometitleplugin.welcometitleplugin
api-version: 1.13
author: raisandesu
depend: []
load: POSTWORLD
website: "https://github.com/uplauncher/welcometitleplugin"
description: Displays a title message when you join the server.
commands:
    wt:
        usage: /wt [help, version]
        description: "You can view help and other information about this plugin and reload the settings."

permissions:
    wt.commands.reload:
        default: false
        description: Allow settings to be reloaded.
    wt.commands.standard:
        default: true
        description: Allow to see help and version.
    wt.show:
        default: true
        description: The title will be displayed.
