#Config of WelcomeTitlePlugin
#WelcomeTitlePlugin の設定

enabled: true
welcome-title:
  title: "&eようこそ！"
  sub-title: "このサーバーへようこそ。"
  fadein: 20 #sec / 秒
  time: 70 #sec / 秒
  fadeout: 20 #sec / 秒
messages:
  prefix: [WT] 
  no-permission: "&cこのコマンドを使用する権限がありません。"
  reloading: "&e設定を再読み込みします..."
  reloaded: "&e設定を再読み込みしました。"
  plugin-enabling-info-first: ""
  plugin-enabling-info-final: " で実行中"
  purpur-title: "-------Purpurを使用する-------"
  purpur-desc1: "Purpur を使用することで、Paper より高いパフォーマンス"
  purpur-desc2: "と便利で簡単な機能を手に入れることができます。"
  purpur-desc3: "tpsbar がデフォルトでついていたり、サーバー名を変更できます。"
  unknown-title: "-------不明なBukkit-------"
  unknown-desc1: "この不明な Bukkit では、確認されていないため実行できません。"
  unknown-desc2: "Purpur をおすすめします: https://purpurmc.org"
  plugin-enabled: "&bWelcomeTitlePlugin &aが有効になりました。"
  plugin-disabled: "&bWelcomeTitlePlugin &aが無効になりました。"
  help-title: "&bWelcomeTitlePlugin - ヘルプ"
  help-desc: "以下のコマンドを使用して、このプラグインを操作します。"
  help-cmd1: "&c/wt help &rこのヘルプを表示します。"
  help-cmd2: "&c/wt version &rこのプラグインのバージョンを表示します。"
  help-cmd3: "&c/wt reload &rこのプラグインの設定を再読み込みします。"
  version-title: "&bWelcomeTitlePlugin"
  version-wt: "バージョン:"
  version-bukkit: "Bukkit:"